const { initDb, run } = require('./connection');

/** Example.com demo users are placed in Bengaluru with spread coordinates for distance matching. */
const BLR = { lat: 12.9716, lon: 77.5946 };

const seedUsers = [
  {
    id: 'a1b2c3d4-0001-4000-8000-000000000001',
    email: 'alex@example.com',
    name: 'Alex Johnson',
    age: 29,
    gender: 'Male',
    profession: 'Product Manager',
    company: 'LinkedIn',
    city: 'San Francisco',
    bio: 'Builder, mentor, and aspiring coffee snob. I love good product, better people, and weekend hikes.',
    photo_url: 'https://images.pexels.com/photos/614810/pexels-photo-614810.jpeg?auto=compress&cs=tinysrgb&w=800',
    interests: '["Product Strategy","Startups","Design","Coffee","Travel"]',
    education: 'MBA, Stanford GSB',
    linkedin_url: 'https://linkedin.com/in/alex',
    is_premium: 1,
  },
  {
    id: 'a1b2c3d4-0001-4000-8000-000000000002',
    email: 'priya@example.com',
    name: 'Priya Sharma',
    age: 27,
    gender: 'Female',
    profession: 'Data Scientist',
    company: 'Stripe',
    city: 'New York',
    bio: 'Turning data into stories. Yoga in the morning, jazz at night.',
    photo_url: 'https://images.pexels.com/photos/1181686/pexels-photo-1181686.jpeg?auto=compress&cs=tinysrgb&w=800',
    interests: '["Data","Yoga","Jazz"]',
    education: 'MS Statistics, MIT',
    linkedin_url: 'https://linkedin.com/in/priya',
    is_premium: 0,
  },
  {
    id: 'a1b2c3d4-0001-4000-8000-000000000003',
    email: 'daniel@example.com',
    name: 'Daniel Kim',
    age: 31,
    gender: 'Male',
    profession: 'Software Engineer',
    company: 'Meta',
    city: 'Seattle',
    bio: 'Climber, foodie, and loyal dog dad. Looking for a co-adventurer.',
    photo_url: 'https://images.pexels.com/photos/2379004/pexels-photo-2379004.jpeg?auto=compress&cs=tinysrgb&w=800',
    interests: '["Climbing","Food","Dogs"]',
    education: 'BS CS, Berkeley',
    linkedin_url: 'https://linkedin.com/in/daniel',
    is_premium: 0,
  },
  {
    id: 'a1b2c3d4-0001-4000-8000-000000000004',
    email: 'ananya@example.com',
    name: 'Ananya Sharma',
    age: 27,
    gender: 'Female',
    profession: 'Product Manager',
    company: 'Amazon',
    city: 'Bangalore',
    bio: 'Building for billions. Chai and curiosity.',
    photo_url: 'https://randomuser.me/api/portraits/women/44.jpg',
    interests: '["Product","Travel","Books"]',
    education: 'B.Tech IIT Delhi',
    linkedin_url: 'https://linkedin.com/in/ananya',
    is_premium: 1,
  },
  {
    id: 'a1b2c3d4-0001-4000-8000-000000000005',
    email: 'rahul@example.com',
    name: 'Rahul Mehta',
    age: 29,
    gender: 'Male',
    profession: 'Software Engineer',
    company: 'Google',
    city: 'Hyderabad',
    bio: 'Code by day, guitar by night.',
    photo_url: 'https://randomuser.me/api/portraits/men/32.jpg',
    interests: '["Music","Open Source"]',
    education: 'B.Tech BITS Pilani',
    linkedin_url: 'https://linkedin.com/in/rahul',
    is_premium: 0,
  },
  {
    id: 'a1b2c3d4-0001-4000-8000-000000000006',
    email: 'maya@example.com',
    name: 'Maya Chen',
    age: 28,
    gender: 'Female',
    profession: 'UX Designer',
    company: 'Figma',
    city: 'San Francisco',
    bio: 'Designing for humans. Coffee, sketching, and long walks.',
    photo_url: 'https://images.pexels.com/photos/774909/pexels-photo-774909.jpeg?auto=compress&cs=tinysrgb&w=800',
    interests: '["Design","Art","Travel","Photography"]',
    education: 'BFA Design, RISD',
    linkedin_url: 'https://linkedin.com/in/maya',
    is_premium: 0,
  },
  {
    id: 'a1b2c3d4-0001-4000-8000-000000000007',
    email: 'james@example.com',
    name: 'James Wilson',
    age: 33,
    gender: 'Male',
    profession: 'Engineering Manager',
    company: 'Netflix',
    city: 'Los Angeles',
    bio: 'Building teams that ship. Runner and podcast addict.',
    photo_url: 'https://images.pexels.com/photos/220453/pexels-photo-220453.jpeg?auto=compress&cs=tinysrgb&w=800',
    interests: '["Leadership","Running","Podcasts","Tech"]',
    education: 'MS CS, Carnegie Mellon',
    linkedin_url: 'https://linkedin.com/in/james',
    is_premium: 1,
  },
  {
    id: 'a1b2c3d4-0001-4000-8000-000000000008',
    email: 'sophie@example.com',
    name: 'Sophie Martin',
    age: 26,
    gender: 'Female',
    profession: 'Marketing Lead',
    company: 'Notion',
    city: 'New York',
    bio: 'Stories that stick. Wine enthusiast and book club host.',
    photo_url: 'https://images.pexels.com/photos/1239291/pexels-photo-1239291.jpeg?auto=compress&cs=tinysrgb&w=800',
    interests: '["Marketing","Writing","Wine","Books"]',
    education: 'BA Communications, NYU',
    linkedin_url: 'https://linkedin.com/in/sophie',
    is_premium: 0,
  },
  {
    id: 'a1b2c3d4-0001-4000-8000-000000000009',
    email: 'omar@example.com',
    name: 'Omar Hassan',
    age: 30,
    gender: 'Male',
    profession: 'Data Engineer',
    company: 'Airbnb',
    city: 'San Francisco',
    bio: 'Pipelines by day, cooking by night. Always exploring.',
    photo_url: 'https://images.pexels.com/photos/1222271/pexels-photo-1222271.jpeg?auto=compress&cs=tinysrgb&w=800',
    interests: '["Data","Cooking","Travel","Hiking"]',
    education: 'BS CS, UCLA',
    linkedin_url: 'https://linkedin.com/in/omar',
    is_premium: 0,
  },
  {
    id: 'a1b2c3d4-0001-4000-8000-000000000010',
    email: 'lisa@example.com',
    name: 'Lisa Park',
    age: 29,
    gender: 'Female',
    profession: 'Product Designer',
    company: 'Spotify',
    city: 'Stockholm',
    bio: 'Music and design. Finding harmony in both.',
    photo_url: 'https://images.pexels.com/photos/1181690/pexels-photo-1181690.jpeg?auto=compress&cs=tinysrgb&w=800',
    interests: '["Design","Music","Running","Minimalism"]',
    education: 'MFA Interaction Design, Konstfack',
    linkedin_url: 'https://linkedin.com/in/lisa',
    is_premium: 1,
  },
  {
    id: 'a1b2c3d4-0001-4000-8000-000000000011',
    email: 'marcus@example.com',
    name: 'Marcus Brown',
    age: 32,
    gender: 'Male',
    profession: 'Sales Director',
    company: 'Salesforce',
    city: 'Austin',
    bio: 'Connecting people and solutions. Golf and grilling on weekends.',
    photo_url: 'https://images.pexels.com/photos/91227/pexels-photo-91227.jpeg?auto=compress&cs=tinysrgb&w=800',
    interests: '["Sales","Golf","BBQ","Podcasts"]',
    education: 'MBA, UT Austin',
    linkedin_url: 'https://linkedin.com/in/marcus',
    is_premium: 0,
  },
  {
    id: 'a1b2c3d4-0001-4000-8000-000000000012',
    email: 'elena@example.com',
    name: 'Elena Rodriguez',
    age: 27,
    gender: 'Female',
    profession: 'Software Engineer',
    company: 'Microsoft',
    city: 'Seattle',
    bio: 'Full-stack and full of curiosity. Love open source and hiking.',
    photo_url: 'https://images.pexels.com/photos/3756165/pexels-photo-3756165.jpeg?auto=compress&cs=tinysrgb&w=800',
    interests: '["Open Source","Hiking","Reading","Coffee"]',
    education: 'BS CS, University of Washington',
    linkedin_url: 'https://linkedin.com/in/elena',
    is_premium: 0,
  },
  // 50 more demo accounts (013–062)
  { id: 'a1b2c3d4-0001-4000-8000-000000000013', email: 'demo13@example.com', name: 'Emma Wilson', age: 28, gender: 'Female', profession: 'HR Manager', company: 'Adobe', city: 'San Jose', bio: 'People-first. Runner and plant mom.', photo_url: 'https://randomuser.me/api/portraits/women/65.jpg', interests: '["HR","Running","Plants"]', education: 'BA Psychology, UCLA', linkedin_url: 'https://linkedin.com/in/demo13', is_premium: 0 },
  { id: 'a1b2c3d4-0001-4000-8000-000000000014', email: 'demo14@example.com', name: 'Ryan Cooper', age: 30, gender: 'Male', profession: 'DevOps Engineer', company: 'Slack', city: 'San Francisco', bio: 'Infrastructure as code. Coffee and keyboards.', photo_url: 'https://randomuser.me/api/portraits/men/22.jpg', interests: '["DevOps","Coffee","Tech"]', education: 'BS CS, Oregon State', linkedin_url: 'https://linkedin.com/in/demo14', is_premium: 0 },
  { id: 'a1b2c3d4-0001-4000-8000-000000000015', email: 'demo15@example.com', name: 'Nina Patel', age: 26, gender: 'Female', profession: 'Content Strategist', company: 'HubSpot', city: 'Boston', bio: 'Stories that convert. Yoga and tea.', photo_url: 'https://randomuser.me/api/portraits/women/26.jpg', interests: '["Content","Yoga","Writing"]', education: 'BA English, Boston University', linkedin_url: 'https://linkedin.com/in/demo15', is_premium: 1 },
  { id: 'a1b2c3d4-0001-4000-8000-000000000016', email: 'demo16@example.com', name: 'Chris Lee', age: 33, gender: 'Male', profession: 'VP Engineering', company: 'Dropbox', city: 'San Francisco', bio: 'Building teams that ship. Dad and cyclist.', photo_url: 'https://randomuser.me/api/portraits/men/45.jpg', interests: '["Leadership","Cycling","Family"]', education: 'MS CS, Stanford', linkedin_url: 'https://linkedin.com/in/demo16', is_premium: 1 },
  { id: 'a1b2c3d4-0001-4000-8000-000000000017', email: 'demo17@example.com', name: 'Zara Ahmed', age: 27, gender: 'Female', profession: 'Financial Analyst', company: 'Goldman Sachs', city: 'New York', bio: 'Numbers and narrative. Travel and food.', photo_url: 'https://randomuser.me/api/portraits/women/33.jpg', interests: '["Finance","Travel","Food"]', education: 'MBA, Wharton', linkedin_url: 'https://linkedin.com/in/demo17', is_premium: 0 },
  { id: 'a1b2c3d4-0001-4000-8000-000000000018', email: 'demo18@example.com', name: 'David Martinez', age: 29, gender: 'Male', profession: 'Frontend Developer', company: 'Vercel', city: 'Austin', bio: 'React by day, guitar by night.', photo_url: 'https://randomuser.me/api/portraits/men/52.jpg', interests: '["React","Music","Open Source"]', education: 'BS CS, UT Austin', linkedin_url: 'https://linkedin.com/in/demo18', is_premium: 0 },
  { id: 'a1b2c3d4-0001-4000-8000-000000000019', email: 'demo19@example.com', name: 'Lily Zhang', age: 25, gender: 'Female', profession: 'Growth Analyst', company: 'Notion', city: 'New York', bio: 'Data-driven growth. Art and running.', photo_url: 'https://randomuser.me/api/portraits/women/44.jpg', interests: '["Growth","Art","Running"]', education: 'BS Economics, NYU', linkedin_url: 'https://linkedin.com/in/demo19', is_premium: 0 },
  { id: 'a1b2c3d4-0001-4000-8000-000000000020', email: 'demo20@example.com', name: 'Kevin O\'Brien', age: 31, gender: 'Male', profession: 'Security Engineer', company: 'Cloudflare', city: 'Austin', bio: 'Keeping the internet safe. Hiking and podcasts.', photo_url: 'https://randomuser.me/api/portraits/men/67.jpg', interests: '["Security","Hiking","Podcasts"]', education: 'MS CS, Georgia Tech', linkedin_url: 'https://linkedin.com/in/demo20', is_premium: 0 },
  { id: 'a1b2c3d4-0001-4000-8000-000000000021', email: 'demo21@example.com', name: 'Sofia Rivera', age: 28, gender: 'Female', profession: 'Legal Counsel', company: 'Stripe', city: 'San Francisco', bio: 'Tech and law. Wine and books.', photo_url: 'https://randomuser.me/api/portraits/women/68.jpg', interests: '["Law","Wine","Books"]', education: 'JD, Harvard Law', linkedin_url: 'https://linkedin.com/in/demo21', is_premium: 1 },
  { id: 'a1b2c3d4-0001-4000-8000-000000000022', email: 'demo22@example.com', name: 'Adam Foster', age: 34, gender: 'Male', profession: 'CTO', company: 'StartupXYZ', city: 'Denver', bio: 'Building the future. Ski and startup life.', photo_url: 'https://randomuser.me/api/portraits/men/75.jpg', interests: '["Tech","Skiing","Startups"]', education: 'PhD CS, MIT', linkedin_url: 'https://linkedin.com/in/demo22', is_premium: 1 },
  { id: 'a1b2c3d4-0001-4000-8000-000000000023', email: 'demo23@example.com', name: 'Mia Thompson', age: 26, gender: 'Female', profession: 'Customer Success', company: 'Zendesk', city: 'Portland', bio: 'Making customers happy. Dogs and coffee.', photo_url: 'https://randomuser.me/api/portraits/women/50.jpg', interests: '["CS","Dogs","Coffee"]', education: 'BA Communications', linkedin_url: 'https://linkedin.com/in/demo23', is_premium: 0 },
  { id: 'a1b2c3d4-0001-4000-8000-000000000024', email: 'demo24@example.com', name: 'Jake Nelson', age: 29, gender: 'Male', profession: 'Backend Engineer', company: 'Twilio', city: 'San Francisco', bio: 'APIs and scale. Surfing and tacos.', photo_url: 'https://randomuser.me/api/portraits/men/33.jpg', interests: '["Backend","Surfing","Food"]', education: 'BS CS, UCSD', linkedin_url: 'https://linkedin.com/in/demo24', is_premium: 0 },
  { id: 'a1b2c3d4-0001-4000-8000-000000000025', email: 'demo25@example.com', name: 'Ava Mitchell', age: 27, gender: 'Female', profession: 'Brand Designer', company: 'Airbnb', city: 'San Francisco', bio: 'Design that tells a story. Photography and travel.', photo_url: 'https://randomuser.me/api/portraits/women/72.jpg', interests: '["Design","Photography","Travel"]', education: 'BFA, SVA', linkedin_url: 'https://linkedin.com/in/demo25', is_premium: 0 },
  { id: 'a1b2c3d4-0001-4000-8000-000000000026', email: 'demo26@example.com', name: 'Tyler Green', age: 30, gender: 'Male', profession: 'Product Lead', company: 'Asana', city: 'San Francisco', bio: 'Shipping product. Basketball and podcasts.', photo_url: 'https://randomuser.me/api/portraits/men/88.jpg', interests: '["Product","Basketball","Podcasts"]', education: 'MBA, Kellogg', linkedin_url: 'https://linkedin.com/in/demo26', is_premium: 1 },
  { id: 'a1b2c3d4-0001-4000-8000-000000000027', email: 'demo27@example.com', name: 'Chloe Davis', age: 25, gender: 'Female', profession: 'Recruiter', company: 'Meta', city: 'Menlo Park', bio: 'Connecting talent with opportunity. Yoga and wine.', photo_url: 'https://randomuser.me/api/portraits/women/85.jpg', interests: '["Recruiting","Yoga","Wine"]', education: 'BA HR, USC', linkedin_url: 'https://linkedin.com/in/demo27', is_premium: 0 },
  { id: 'a1b2c3d4-0001-4000-8000-000000000028', email: 'demo28@example.com', name: 'Brandon Wright', age: 32, gender: 'Male', profession: 'ML Engineer', company: 'OpenAI', city: 'San Francisco', bio: 'Models and data. Chess and hiking.', photo_url: 'https://randomuser.me/api/portraits/men/91.jpg', interests: '["ML","Chess","Hiking"]', education: 'PhD ML, Stanford', linkedin_url: 'https://linkedin.com/in/demo28', is_premium: 1 },
  { id: 'a1b2c3d4-0001-4000-8000-000000000029', email: 'demo29@example.com', name: 'Hannah Clark', age: 28, gender: 'Female', profession: 'Operations Manager', company: 'DoorDash', city: 'San Francisco', bio: 'Keeping things running. Cooking and travel.', photo_url: 'https://randomuser.me/api/portraits/women/90.jpg', interests: '["Ops","Cooking","Travel"]', education: 'BS Business, Berkeley', linkedin_url: 'https://linkedin.com/in/demo29', is_premium: 0 },
  { id: 'a1b2c3d4-0001-4000-8000-000000000030', email: 'demo30@example.com', name: 'Nathan Hall', age: 27, gender: 'Male', profession: 'QA Engineer', company: 'Atlassian', city: 'Sydney', bio: 'Quality first. Gaming and coffee.', photo_url: 'https://randomuser.me/api/portraits/men/11.jpg', interests: '["QA","Gaming","Coffee"]', education: 'BS CS, UNSW', linkedin_url: 'https://linkedin.com/in/demo30', is_premium: 0 },
  { id: 'a1b2c3d4-0001-4000-8000-000000000031', email: 'demo31@example.com', name: 'Grace Kim', age: 26, gender: 'Female', profession: 'Investment Analyst', company: 'Sequoia', city: 'Menlo Park', bio: 'Backing builders. Running and reading.', photo_url: 'https://randomuser.me/api/portraits/women/12.jpg', interests: '["VC","Running","Books"]', education: 'MBA, Stanford', linkedin_url: 'https://linkedin.com/in/demo31', is_premium: 1 },
  { id: 'a1b2c3d4-0001-4000-8000-000000000032', email: 'demo32@example.com', name: 'Jordan Taylor', age: 29, gender: 'Male', profession: 'Solutions Architect', company: 'AWS', city: 'Seattle', bio: 'Cloud and scale. Mountain biking and beer.', photo_url: 'https://randomuser.me/api/portraits/men/15.jpg', interests: '["Cloud","Biking","Beer"]', education: 'MS CS, UW', linkedin_url: 'https://linkedin.com/in/demo32', is_premium: 0 },
  { id: 'a1b2c3d4-0001-4000-8000-000000000033', email: 'demo33@example.com', name: 'Olivia White', age: 24, gender: 'Female', profession: 'Social Media Manager', company: 'TikTok', city: 'Los Angeles', bio: 'Viral by design. Dance and photography.', photo_url: 'https://randomuser.me/api/portraits/women/18.jpg', interests: '["Social","Dance","Photography"]', education: 'BA Marketing, UCLA', linkedin_url: 'https://linkedin.com/in/demo33', is_premium: 0 },
  { id: 'a1b2c3d4-0001-4000-8000-000000000034', email: 'demo34@example.com', name: 'Ethan Scott', age: 31, gender: 'Male', profession: 'Technical Writer', company: 'Google', city: 'Mountain View', bio: 'Docs that developers love. Hiking and sci-fi.', photo_url: 'https://randomuser.me/api/portraits/men/25.jpg', interests: '["Writing","Hiking","Sci-fi"]', education: 'BA English, Stanford', linkedin_url: 'https://linkedin.com/in/demo34', is_premium: 0 },
  { id: 'a1b2c3d4-0001-4000-8000-000000000035', email: 'demo35@example.com', name: 'Isabella Garcia', age: 27, gender: 'Female', profession: 'UX Researcher', company: 'Nielsen', city: 'Chicago', bio: 'User voices into product. Cooking and podcasts.', photo_url: 'https://randomuser.me/api/portraits/women/28.jpg', interests: '["Research","Cooking","Podcasts"]', education: 'MS HCI, CMU', linkedin_url: 'https://linkedin.com/in/demo35', is_premium: 0 },
  { id: 'a1b2c3d4-0001-4000-8000-000000000036', email: 'demo36@example.com', name: 'Logan Adams', age: 28, gender: 'Male', profession: 'Mobile Developer', company: 'Uber', city: 'San Francisco', bio: 'iOS and Android. Coffee and running.', photo_url: 'https://randomuser.me/api/portraits/men/30.jpg', interests: '["Mobile","Coffee","Running"]', education: 'BS CS, Purdue', linkedin_url: 'https://linkedin.com/in/demo36', is_premium: 0 },
  { id: 'a1b2c3d4-0001-4000-8000-000000000037', email: 'demo37@example.com', name: 'Abigail Lewis', age: 26, gender: 'Female', profession: 'Event Manager', company: 'Eventbrite', city: 'San Francisco', bio: 'Bringing people together. Wine and travel.', photo_url: 'https://randomuser.me/api/portraits/women/35.jpg', interests: '["Events","Wine","Travel"]', education: 'BA Hospitality', linkedin_url: 'https://linkedin.com/in/demo37', is_premium: 0 },
  { id: 'a1b2c3d4-0001-4000-8000-000000000038', email: 'demo38@example.com', name: 'Mason King', age: 33, gender: 'Male', profession: 'Data Architect', company: 'Snowflake', city: 'Bozeman', bio: 'Data at scale. Skiing and fly fishing.', photo_url: 'https://randomuser.me/api/portraits/men/42.jpg', interests: '["Data","Skiing","Fishing"]', education: 'MS CS, Montana State', linkedin_url: 'https://linkedin.com/in/demo38', is_premium: 1 },
  { id: 'a1b2c3d4-0001-4000-8000-000000000039', email: 'demo39@example.com', name: 'Charlotte Walker', age: 25, gender: 'Female', profession: 'Copywriter', company: 'Mailchimp', city: 'Atlanta', bio: 'Words that convert. Yoga and tea.', photo_url: 'https://randomuser.me/api/portraits/women/40.jpg', interests: '["Copy","Yoga","Tea"]', education: 'BA Creative Writing', linkedin_url: 'https://linkedin.com/in/demo39', is_premium: 0 },
  { id: 'a1b2c3d4-0001-4000-8000-000000000040', email: 'demo40@example.com', name: 'Lucas Hill', age: 30, gender: 'Male', profession: 'Compliance Officer', company: 'Plaid', city: 'San Francisco', bio: 'Keeping fintech safe. Golf and reading.', photo_url: 'https://randomuser.me/api/portraits/men/55.jpg', interests: '["Compliance","Golf","Reading"]', education: 'JD, Georgetown', linkedin_url: 'https://linkedin.com/in/demo40', is_premium: 0 },
  { id: 'a1b2c3d4-0001-4000-8000-000000000041', email: 'demo41@example.com', name: 'Amelia Young', age: 28, gender: 'Female', profession: 'Strategy Consultant', company: 'McKinsey', city: 'New York', bio: 'Solving hard problems. Travel and food.', photo_url: 'https://randomuser.me/api/portraits/women/48.jpg', interests: '["Strategy","Travel","Food"]', education: 'MBA, INSEAD', linkedin_url: 'https://linkedin.com/in/demo41', is_premium: 1 },
  { id: 'a1b2c3d4-0001-4000-8000-000000000042', email: 'demo42@example.com', name: 'Aiden Baker', age: 27, gender: 'Male', profession: 'Game Developer', company: 'Unity', city: 'San Francisco', bio: 'Building worlds. Gaming and music.', photo_url: 'https://randomuser.me/api/portraits/men/62.jpg', interests: '["Games","Music","Tech"]', education: 'BS Game Dev, DigiPen', linkedin_url: 'https://linkedin.com/in/demo42', is_premium: 0 },
  { id: 'a1b2c3d4-0001-4000-8000-000000000043', email: 'demo43@example.com', name: 'Harper Gonzalez', age: 26, gender: 'Female', profession: 'Community Manager', company: 'Discord', city: 'San Francisco', bio: 'Building communities. Gaming and art.', photo_url: 'https://randomuser.me/api/portraits/women/55.jpg', interests: '["Community","Gaming","Art"]', education: 'BA Communications', linkedin_url: 'https://linkedin.com/in/demo43', is_premium: 0 },
  { id: 'a1b2c3d4-0001-4000-8000-000000000044', email: 'demo44@example.com', name: 'Jackson Perez', age: 29, gender: 'Male', profession: 'Sales Engineer', company: 'Datadog', city: 'New York', bio: 'Technical sales. Running and coffee.', photo_url: 'https://randomuser.me/api/portraits/men/70.jpg', interests: '["Sales","Running","Coffee"]', education: 'BS EE, MIT', linkedin_url: 'https://linkedin.com/in/demo44', is_premium: 0 },
  { id: 'a1b2c3d4-0001-4000-8000-000000000045', email: 'demo45@example.com', name: 'Evelyn Turner', age: 27, gender: 'Female', profession: 'Product Analyst', company: 'Amplitude', city: 'San Francisco', bio: 'Data-informed product. Yoga and wine.', photo_url: 'https://randomuser.me/api/portraits/women/60.jpg', interests: '["Analytics","Yoga","Wine"]', education: 'MS Data Science, Columbia', linkedin_url: 'https://linkedin.com/in/demo45', is_premium: 0 },
  { id: 'a1b2c3d4-0001-4000-8000-000000000046', email: 'demo46@example.com', name: 'Sebastian Phillips', age: 32, gender: 'Male', profession: 'Engineering Manager', company: 'GitHub', city: 'San Francisco', bio: 'Leading engineers. Dad and cyclist.', photo_url: 'https://randomuser.me/api/portraits/men/78.jpg', interests: '["Engineering","Family","Cycling"]', education: 'MS CS, Berkeley', linkedin_url: 'https://linkedin.com/in/demo46', is_premium: 1 },
  { id: 'a1b2c3d4-0001-4000-8000-000000000047', email: 'demo47@example.com', name: 'Victoria Campbell', age: 25, gender: 'Female', profession: 'Talent Partner', company: 'Andreessen Horowitz', city: 'Menlo Park', bio: 'Finding exceptional people. Running and books.', photo_url: 'https://randomuser.me/api/portraits/women/63.jpg', interests: '["Talent","Running","Books"]', education: 'BA Psychology, Stanford', linkedin_url: 'https://linkedin.com/in/demo47', is_premium: 0 },
  { id: 'a1b2c3d4-0001-4000-8000-000000000048', email: 'demo48@example.com', name: 'Henry Parker', age: 31, gender: 'Male', profession: 'Infrastructure Engineer', company: 'Hashicorp', city: 'Austin', bio: 'Infra as code. BBQ and hiking.', photo_url: 'https://randomuser.me/api/portraits/men/82.jpg', interests: '["Infra","BBQ","Hiking"]', education: 'BS CS, Texas A&M', linkedin_url: 'https://linkedin.com/in/demo48', is_premium: 0 },
  { id: 'a1b2c3d4-0001-4000-8000-000000000049', email: 'demo49@example.com', name: 'Scarlett Evans', age: 28, gender: 'Female', profession: 'Partnerships Manager', company: 'Shopify', city: 'Ottawa', bio: 'Building partnerships. Travel and food.', photo_url: 'https://randomuser.me/api/portraits/women/74.jpg', interests: '["Partnerships","Travel","Food"]', education: 'MBA, Rotman', linkedin_url: 'https://linkedin.com/in/demo49', is_premium: 0 },
  { id: 'a1b2c3d4-0001-4000-8000-000000000050', email: 'demo50@example.com', name: 'Oliver Edwards', age: 29, gender: 'Male', profession: 'Design Engineer', company: 'Linear', city: 'San Francisco', bio: 'Design and code. Coffee and design systems.', photo_url: 'https://randomuser.me/api/portraits/men/86.jpg', interests: '["Design","Code","Coffee"]', education: 'BFA + CS minor, RISD', linkedin_url: 'https://linkedin.com/in/demo50', is_premium: 0 },
  { id: 'a1b2c3d4-0001-4000-8000-000000000051', email: 'demo51@example.com', name: 'Aria Collins', age: 26, gender: 'Female', profession: 'Sustainability Lead', company: 'Patagonia', city: 'Ventura', bio: 'Planet and people. Surfing and outdoors.', photo_url: 'https://randomuser.me/api/portraits/women/77.jpg', interests: '["Sustainability","Surfing","Outdoors"]', education: 'MS Environmental, Yale', linkedin_url: 'https://linkedin.com/in/demo51', is_premium: 0 },
  { id: 'a1b2c3d4-0001-4000-8000-000000000052', email: 'demo52@example.com', name: 'Liam Stewart', age: 30, gender: 'Male', profession: 'Support Lead', company: 'Intercom', city: 'Dublin', bio: 'Helping customers win. Soccer and pubs.', photo_url: 'https://randomuser.me/api/portraits/men/94.jpg', interests: '["Support","Soccer","Travel"]', education: 'BA Business, Trinity', linkedin_url: 'https://linkedin.com/in/demo52', is_premium: 0 },
  { id: 'a1b2c3d4-0001-4000-8000-000000000053', email: 'demo53@example.com', name: 'Layla Morris', age: 27, gender: 'Female', profession: 'BI Analyst', company: 'Looker', city: 'Boulder', bio: 'Data and dashboards. Skiing and coffee.', photo_url: 'https://randomuser.me/api/portraits/women/80.jpg', interests: '["BI","Skiing","Coffee"]', education: 'MS Analytics, CU Boulder', linkedin_url: 'https://linkedin.com/in/demo53', is_premium: 0 },
  { id: 'a1b2c3d4-0001-4000-8000-000000000054', email: 'demo54@example.com', name: 'Noah Murphy', age: 28, gender: 'Male', profession: 'Platform Engineer', company: 'Segment', city: 'San Francisco', bio: 'Platform that scales. Running and podcasts.', photo_url: 'https://randomuser.me/api/portraits/men/96.jpg', interests: '["Platform","Running","Podcasts"]', education: 'BS CS, Cal Poly', linkedin_url: 'https://linkedin.com/in/demo54', is_premium: 0 },
  { id: 'a1b2c3d4-0001-4000-8000-000000000055', email: 'demo55@example.com', name: 'Zoey Cook', age: 25, gender: 'Female', profession: 'Editor', company: 'Substack', city: 'Brooklyn', bio: 'Stories that matter. Books and coffee.', photo_url: 'https://randomuser.me/api/portraits/women/82.jpg', interests: '["Writing","Books","Coffee"]', education: 'BA Journalism, Northwestern', linkedin_url: 'https://linkedin.com/in/demo55', is_premium: 0 },
  { id: 'a1b2c3d4-0001-4000-8000-000000000056', email: 'demo56@example.com', name: 'Elijah Rogers', age: 33, gender: 'Male', profession: 'Principal Engineer', company: 'Stripe', city: 'South San Francisco', bio: 'Systems and scale. Father and runner.', photo_url: 'https://randomuser.me/api/portraits/men/99.jpg', interests: '["Systems","Running","Family"]', education: 'PhD CS, Stanford', linkedin_url: 'https://linkedin.com/in/demo56', is_premium: 1 },
  { id: 'a1b2c3d4-0001-4000-8000-000000000057', email: 'demo57@example.com', name: 'Penelope Reed', age: 26, gender: 'Female', profession: 'Account Executive', company: 'Salesforce', city: 'Chicago', bio: 'Closing deals. Yoga and wine.', photo_url: 'https://randomuser.me/api/portraits/women/86.jpg', interests: '["Sales","Yoga","Wine"]', education: 'BA Business, DePaul', linkedin_url: 'https://linkedin.com/in/demo57', is_premium: 0 },
  { id: 'a1b2c3d4-0001-4000-8000-000000000058', email: 'demo58@example.com', name: 'Lucas Morgan', age: 29, gender: 'Male', profession: 'DevRel', company: 'Vercel', city: 'San Francisco', bio: 'Developer experience. Open source and talks.', photo_url: 'https://randomuser.me/api/portraits/men/14.jpg', interests: '["DevRel","OSS","Speaking"]', education: 'BS CS, MIT', linkedin_url: 'https://linkedin.com/in/demo58', is_premium: 0 },
  { id: 'a1b2c3d4-0001-4000-8000-000000000059', email: 'demo59@example.com', name: 'Hazel Bell', age: 28, gender: 'Female', profession: 'Procurement Manager', company: 'Tesla', city: 'Fremont', bio: 'Supply chain and sustainability. Hiking and reading.', photo_url: 'https://randomuser.me/api/portraits/women/88.jpg', interests: '["Procurement","Hiking","Reading"]', education: 'MBA, Haas', linkedin_url: 'https://linkedin.com/in/demo59', is_premium: 0 },
  { id: 'a1b2c3d4-0001-4000-8000-000000000060', email: 'demo60@example.com', name: 'Mason Murphy', age: 30, gender: 'Male', profession: 'Technical PM', company: 'Figma', city: 'San Francisco', bio: 'Shipping at the intersection of design and eng. Coffee and design.', photo_url: 'https://randomuser.me/api/portraits/men/17.jpg', interests: '["PM","Design","Coffee"]', education: 'MS ECE, Stanford', linkedin_url: 'https://linkedin.com/in/demo60', is_premium: 0 },
  { id: 'a1b2c3d4-0001-4000-8000-000000000061', email: 'demo61@example.com', name: 'Stella Bailey', age: 27, gender: 'Female', profession: 'Risk Analyst', company: 'Square', city: 'San Francisco', bio: 'Risk and compliance. Running and travel.', photo_url: 'https://randomuser.me/api/portraits/women/92.jpg', interests: '["Risk","Running","Travel"]', education: 'MS Finance, Chicago', linkedin_url: 'https://linkedin.com/in/demo61', is_premium: 0 },
  { id: 'a1b2c3d4-0001-4000-8000-000000000062', email: 'demo62@example.com', name: 'Lucas Rivera', age: 31, gender: 'Male', profession: 'Staff Engineer', company: 'Netflix', city: 'Los Gatos', bio: 'Distributed systems. Dad and mountain biking.', photo_url: 'https://randomuser.me/api/portraits/men/19.jpg', interests: '["Distributed Systems","Biking","Family"]', education: 'MS CS, UCLA', linkedin_url: 'https://linkedin.com/in/demo62', is_premium: 1 },
];

async function seed() {
  await initDb();
  for (let i = 0; i < seedUsers.length; i++) {
    const u = seedUsers[i];
    const t = (i / Math.max(seedUsers.length, 1)) * 2 * Math.PI;
    const r = 0.012 * (0.5 + ((i % 7) / 7));
    const lat = BLR.lat + r * Math.cos(t);
    const lon = BLR.lon + r * Math.sin(t);
    await run(
      `INSERT INTO users (
        id, email, name, age, gender, profession, company, city, bio, photo_url, interests, education, linkedin_url, is_premium, latitude, longitude, created_at, updated_at
      ) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, NOW(), NOW())
      ON CONFLICT (id) DO NOTHING`,
      [
        u.id,
        u.email,
        u.name,
        u.age,
        u.gender,
        u.profession,
        u.company,
        'Bengaluru',
        u.bio,
        u.photo_url,
        u.interests,
        u.education,
        u.linkedin_url,
        u.is_premium,
        lat,
        lon,
      ],
    );
  }

  const genderById = Object.fromEntries(seedUsers.map((u) => [u.id, u.gender]));
  for (const [id, gender] of Object.entries(genderById)) {
    if (gender) {
      await run("UPDATE users SET gender = ? WHERE id = ? AND (gender IS NULL OR gender = '')", [
        gender,
        id,
      ]);
    }
  }

  console.log('Seeded', seedUsers.length, 'users. Use OTP_FIXED_CODE or Resend for OTP in production.');
}

seed().catch((e) => {
  console.error(e);
  process.exit(1);
});
